/**
 * This class is generated by jOOQ
 */
package net.kr9ly.thinfw.db;


import javax.annotation.Generated;

import net.kr9ly.thinfw.db.tables.SchemaVersion;
import net.kr9ly.thinfw.db.tables.Usercredentials;
import net.kr9ly.thinfw.db.tables.Users;


/**
 * Convenience access to all tables in thinfw
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table thinfw.schema_version
	 */
	public static final SchemaVersion SCHEMA_VERSION = net.kr9ly.thinfw.db.tables.SchemaVersion.SCHEMA_VERSION;

	/**
	 * The table thinfw.UserCredentials
	 */
	public static final Usercredentials USERCREDENTIALS = net.kr9ly.thinfw.db.tables.Usercredentials.USERCREDENTIALS;

	/**
	 * The table thinfw.User
	 */
	public static final Users USERS = net.kr9ly.thinfw.db.tables.Users.USERS;
}
