/**
 * This class is generated by jOOQ
 */
package net.kr9ly.thinfw.db;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import net.kr9ly.thinfw.db.tables.SchemaVersion;
import net.kr9ly.thinfw.db.tables.Usercredentials;
import net.kr9ly.thinfw.db.tables.Users;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Thinfw extends SchemaImpl {

	private static final long serialVersionUID = -1697127751;

	/**
	 * The reference instance of <code>thinfw</code>
	 */
	public static final Thinfw THINFW = new Thinfw();

	/**
	 * No further instances allowed
	 */
	private Thinfw() {
		super("thinfw");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			SchemaVersion.SCHEMA_VERSION,
			Usercredentials.USERCREDENTIALS,
			Users.USERS);
	}
}
