/**
 * This class is generated by jOOQ
 */
package net.kr9ly.thinfw.db.tables.records;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import net.kr9ly.thinfw.db.tables.Users;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record4<Long, String, LocalDateTime, LocalDateTime> {

	private static final long serialVersionUID = -1548459006;

	/**
	 * Setter for <code>thinfw.User.userId</code>.
	 */
	public void setUserid(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>thinfw.User.userId</code>.
	 */
	public Long getUserid() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>thinfw.User.userName</code>.
	 */
	public void setUsername(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>thinfw.User.userName</code>.
	 */
	public String getUsername() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>thinfw.User.createdAt</code>.
	 */
	public void setCreatedat(LocalDateTime value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>thinfw.User.createdAt</code>.
	 */
	public LocalDateTime getCreatedat() {
		return (LocalDateTime) getValue(2);
	}

	/**
	 * Setter for <code>thinfw.User.updatedAt</code>.
	 */
	public void setUpdatedat(LocalDateTime value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>thinfw.User.updatedAt</code>.
	 */
	public LocalDateTime getUpdatedat() {
		return (LocalDateTime) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, String, LocalDateTime, LocalDateTime> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, String, LocalDateTime, LocalDateTime> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return Users.USERS.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Users.USERS.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<LocalDateTime> field3() {
		return Users.USERS.CREATEDAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<LocalDateTime> field4() {
		return Users.USERS.UPDATEDAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LocalDateTime value3() {
		return getCreatedat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LocalDateTime value4() {
		return getUpdatedat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value1(Long value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value2(String value) {
		setUsername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value3(LocalDateTime value) {
		setCreatedat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value4(LocalDateTime value) {
		setUpdatedat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord values(Long value1, String value2, LocalDateTime value3, LocalDateTime value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsersRecord
	 */
	public UsersRecord() {
		super(Users.USERS);
	}

	/**
	 * Create a detached, initialised UsersRecord
	 */
	public UsersRecord(Long userid, String username, LocalDateTime createdat, LocalDateTime updatedat) {
		super(Users.USERS);

		setValue(0, userid);
		setValue(1, username);
		setValue(2, createdat);
		setValue(3, updatedat);
	}
}
