/**
 * This class is generated by jOOQ
 */
package net.kr9ly.thinfw.db.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import net.kr9ly.thinfw.converter.LocalDateTimeConverter;
import net.kr9ly.thinfw.db.Keys;
import net.kr9ly.thinfw.db.Thinfw;
import net.kr9ly.thinfw.db.tables.records.UsercredentialsRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Usercredentials extends TableImpl<UsercredentialsRecord> {

	private static final long serialVersionUID = 1206321778;

	/**
	 * The reference instance of <code>thinfw.UserCredentials</code>
	 */
	public static final Usercredentials USERCREDENTIALS = new Usercredentials();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UsercredentialsRecord> getRecordType() {
		return UsercredentialsRecord.class;
	}

	/**
	 * The column <code>thinfw.UserCredentials.userId</code>.
	 */
	public final TableField<UsercredentialsRecord, Long> USERID = createField("userId", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>thinfw.UserCredentials.authKey</code>.
	 */
	public final TableField<UsercredentialsRecord, String> AUTHKEY = createField("authKey", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>thinfw.UserCredentials.passwordHash</code>.
	 */
	public final TableField<UsercredentialsRecord, String> PASSWORDHASH = createField("passwordHash", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>thinfw.UserCredentials.createdAt</code>.
	 */
	public final TableField<UsercredentialsRecord, LocalDateTime> CREATEDAT = createField("createdAt", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "", new LocalDateTimeConverter());

	/**
	 * The column <code>thinfw.UserCredentials.updatedAt</code>.
	 */
	public final TableField<UsercredentialsRecord, LocalDateTime> UPDATEDAT = createField("updatedAt", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "", new LocalDateTimeConverter());

	/**
	 * Create a <code>thinfw.UserCredentials</code> table reference
	 */
	public Usercredentials() {
		this("UserCredentials", null);
	}

	/**
	 * Create an aliased <code>thinfw.UserCredentials</code> table reference
	 */
	public Usercredentials(String alias) {
		this(alias, USERCREDENTIALS);
	}

	private Usercredentials(String alias, Table<UsercredentialsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Usercredentials(String alias, Table<UsercredentialsRecord> aliased, Field<?>[] parameters) {
		super(alias, Thinfw.THINFW, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<UsercredentialsRecord> getPrimaryKey() {
		return Keys.KEY_USERCREDENTIALS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<UsercredentialsRecord>> getKeys() {
		return Arrays.<UniqueKey<UsercredentialsRecord>>asList(Keys.KEY_USERCREDENTIALS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Usercredentials as(String alias) {
		return new Usercredentials(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Usercredentials rename(String name) {
		return new Usercredentials(name, null);
	}
}
